/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "Funciones_banco.h"



void
funciones_banco_1(char *host){
	int ejecutar;
	do{
			CLIENT *clnt;
			char * *result_1;
			mensaje  msj_1_arg;
			printf("=======================\n");
			printf("TRANSACCIONES BANCARIAS\n");
			printf("=======================\n");
			printf("Ingrese el tipo de transación que desea realizar:\n");
			printf("1. Depósito\n");
			printf("2. Retiro\n");
			printf("- Selección: ");
			scanf("%i", &msj_1_arg.seleccion);
			printf("---------------------------------------------\n");
			printf("Inserte la cantidad: ");
			scanf("%i", &msj_1_arg.dinero);
			printf("---------------------------------------------\n");

		#ifndef	DEBUG
			clnt = clnt_create (host, FUNCIONES_BANCO, VERSION_MENSAJE, "udp");
			if (clnt == NULL) {
				clnt_pcreateerror (host);
				exit (1);
			}
		#endif	/* DEBUG */

			result_1 = msj_1(&msj_1_arg, clnt);
			printf("%s\n",*result_1);
			printf("---------------------------------------------\n");
			printf("\n~ ¿Desea continuar realizando transacciones (Sí = 3)?: ");
			scanf("%d", &ejecutar);
			printf("\n");
			if (result_1 == (char **) NULL) {
				clnt_perror (clnt, "call failed");
			}
		#ifndef	DEBUG
			clnt_destroy (clnt);
		#endif	 /* DEBUG */
	} while (ejecutar == 3);
	
}

int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	funciones_banco_1 (host);
exit (0);
}
