/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "Funciones_banco.h"

bool_t
xdr_mensaje (XDR *xdrs, mensaje *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->seleccion))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->dinero))
		 return FALSE;
	return TRUE;
}
