/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "Funciones_banco.h"

char **
msj_1_svc(mensaje *argp, struct svc_req *rqstp)
{
	static char * result;
	char msj1[] = "Su depósito es de $";
	char msj2[] = "Su retiro es de $";
	char textCant[10];
	sprintf(textCant,"%i",argp->dinero);
	printf("%s",textCant);
	int seleccion = argp->seleccion;
	printf("%i",seleccion);

	if (seleccion == 1) {
		strcat(msj1,textCant);
		result = strdup(msj1);
	}else if (seleccion == 2) {
		strcat(msj2,textCant);
		result = strdup(msj2);
	}else{
		result = strdup("");
	}

	return &result;
}
